### ISSUE TITLE
Setup own "Group & Folder Colors"

### ISSUE THREAD

**Issue by vasylnakvasiuk** [nilium/st2-nil-theme#16]
Add in config not only true/false, but also custom colors.

**Comment by vasylnakvasiuk** [comment]
Or make folder color - "blue" :) :+1:

**Comment by nilium** [comment]
Blue is for highlights and active UI items and you cannot specify colors in a config file. Neither of these things are changing. Further requests for this will also be rejected.

**Comment by vasylnakvasiuk** [comment]
Maybe, add some possibility to customize these colors? Some config variables.

**Comment by nilium** [comment]
I don't want to bloat the theme with tons of configuration preferences like certain other themes do. I put in preferences to disable the coloring because it was a change after so long, but I'm not going to cram the theme full of unused crap (like the Phoenix theme). If you want to change the color for some reason, modify the theme or create an additional (Nil|Ayin).sublime-theme file in your user directory with your customizations.

My recommendation: stick with purple. You'll come to appreciate it.
