### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by larzconwell** [nilium/st2-nil-theme#4]
This is an amazing theme! I'd love to see a light version that's whites and greys! 

Also in the theme, the borders for the sidebar and tab are a little bright compared to everything else (:

**Comment by nilium** [comment]
**re: A light theme**

I've been pondering it.  Waiting to see what happens pending any changes to Sublime for HDPI (which would be welcomed, seeing as I've got a new MacBook Pro on the way).  It'll probably mean updating all of the images in the theme, so I don't really want to do anything 'til I see how that pans out.

---

**re: The borders**, they're bright mainly so I can pick them out easily. I use the sidebar a lot, so I don't really like fishing around for that one pixel I need to drag in order to resize it. As for the tabs, I just like the way it looks (panels have a similar border).

If you want to change the sidebar color, you can do so by modifying the `sidebar_container` property `layer0.tint` (RGB values).  The tab border is part of the tab/container image, so you'd have to fire up Photoshop or something for that. You'd just need to modify 'tab-inactive.png' and 'tabset-bg.png'.

At any rate, I don't have any plans to change those bits.  Best advice I can offer for now is to fork it, change it, and share it, that way there're more options for anyone interested.

**Comment by larzconwell** [comment]
Okay cool, I can't way then! :D 

I was just curious why they were a bit brighter, I already changed them though (: Thanks!

**Comment by nilium** [comment]
I'll leave this open for now since the light theme thing hasn't really been addressed yet.

**Comment by nilium** [comment]
Jon's detailed the HDPI situation, going to get started on updating the theme for HDPI along with this tomorrow-ish.

Some things might have to change in subtle ways just to accommodate the absurd resolution of the new MBP.

**Comment by larzconwell** [comment]
Haha yeah I figured it would be a little different, awesome!

**Comment by nilium** [comment]
Well, it's coming along.

![](http://f.cl.ly/items/3x2A1O2O2N07413I3J2H/Screen%20Shot%202012-06-17%20at%206.48.20%20PM.png)

**Comment by larzconwell** [comment]
Oh my, that is very nice. I like it very much!
